export {
  detectUrls,
  shouldAutoFetch,
  getUrlsToPrefetch,
  prefetchUrls,
  processMessageForUrls,
  formatUrlContextsForPrompt,
  preprocessInput,
  preprocessConversation,
  replaceUrlPlaceholders,
  isUrlPlaceholder,
  getOriginalUrl,
  resetUrlPlaceholderCounter,
  type DetectedUrl,
  type UrlContext,
  type ProcessedMessage,
  type PreprocessedInput,
  type PreprocessedConversation,
} from './urlDetector';
